### ISSUE TITLE
unable to run the script

### ISSUE THREAD

**Issue by tanaysoni** [y13i/sensu-plugin-metrics-mongostat#1]
`ruby metrics-mongostat.rb` gives the following error:
```
Error parsing command line: unknown option json
try 'mongostat --help' for more information
test.rb:120:in `mongostat_result'
test.rb:51:in `block in run'
test.rb:47:in `upto'
test.rb:47:in `run'
/var/lib/gems/1.9.1/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'
Error: undefined method `values' for nil:NilClass
```

**Comment by y13i** [comment]
what version of mongodb-org-tools you use?

**Comment by tanaysoni** [comment]
version 2.6.9

**Comment by y13i** [comment]
https://jira.mongodb.org/browse/TOOLS-322

it looks like `--json` feature added to mongostat >= 2.8.0.
this plugin uses `mongostat --json`, so you should upgrade your mongodb-org-tools.

**Comment by tanaysoni** [comment]
Thank you for sorting this out. I was wondering if there is any workaround and not use the JSON feature?
